# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SosomLab.NexaSQL
PackageVersion: 0.1.5
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
AppsAndFeaturesEntries:
- DisplayName: Nexa SQL
  Publisher: SosomLab
  ProductCode: '{A2F01FD8-3DCE-4915-B59C-6FC9DF2B39A6}'
  UpgradeCode: '{B404C009-2003-4CD7-B231-113BA00242E2}'
  InstallerType: wix
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/SosomLab/nexa-sql/releases/download/v0.1.5/nexa-sql-0.1.5-windows-x64.msi
  InstallerSha256: D528132122603C67162884BB0C87FB03222FA8D7F98FA39563330800245C3C8B
  ProductCode: '{A2F01FD8-3DCE-4915-B59C-6FC9DF2B39A6}'
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-05
