# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: SosomLab.NexaClip.Portable
PackageVersion: 0.1.6
MinimumOSVersion: 10.0.0.0
InstallerType: zip
NestedInstallerType: portable
UpgradeBehavior: install
Commands:
- nexa-clip
Installers:
- Architecture: x64
  NestedInstallerFiles:
  - RelativeFilePath: nexa-clip-0.1.6-windows-x64-portable\nexa-clip.exe
    PortableCommandAlias: nexa-clip
  InstallerUrl: https://github.com/SosomLab/nexa-clip/releases/download/v0.1.6/nexa-clip-0.1.6-windows-x64-portable.zip
  InstallerSha256: 621fcb4efaaa07aaebf4d139834ad3b2693f9b6162af1f70116836b764835fb5
- Architecture: arm64
  NestedInstallerFiles:
  - RelativeFilePath: nexa-clip-0.1.6-windows-arm64-portable\nexa-clip.exe
    PortableCommandAlias: nexa-clip
  InstallerUrl: https://github.com/SosomLab/nexa-clip/releases/download/v0.1.6/nexa-clip-0.1.6-windows-arm64-portable.zip
  InstallerSha256: 44f7e85bcf1ef3e85d48e1454872ef072bf83b0cd0385bae02298be71084c413
ManifestType: installer
ManifestVersion: 1.6.0
ReleaseDate: 2026-10-04
