# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: SosomLab.NexaClip
PackageVersion: 0.1.6
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: NexaClip
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/SosomLab/nexa-clip/releases/download/v0.1.6/nexa-clip-0.1.6-windows-x64-setup.exe
  InstallerSha256: ac82a9acf053a76493b9aeb2c48a46f3896af98785c17b17b79b87239b1a1e29
- Architecture: arm64
  InstallerUrl: https://github.com/SosomLab/nexa-clip/releases/download/v0.1.6/nexa-clip-0.1.6-windows-arm64-setup.exe
  InstallerSha256: 27c4e3ed871ffa25c7967fb2cc8cf8ed41771870643ae9935613937c5fe3606e
ManifestType: installer
ManifestVersion: 1.6.0
ReleaseDate: 2026-10-04
